-- ====================================================================
-- AGROSAT - SCRIPT DDL ORACLE DATABASE
-- Disciplina: Global Solution
-- ====================================================================

-- 1. TABELA DE HISTÓRICO DE BUSCAS / MONITORAMENTO SATÉLITE
CREATE TABLE TB_AGRO_BUSCA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude NUMBER(9,6) NOT NULL,
    longitude NUMBER(9,6) NOT NULL,
    temp_media NUMBER(5,2),
    temp_max NUMBER(5,2),
    temp_min NUMBER(5,2),
    precip_total NUMBER(6,2),
    umidade_media NUMBER(5,2),
    rad_solar_media NUMBER(6,2),
    ndvi_valor NUMBER(3,2),
    classificacao_ndvi VARCHAR2(100),
    data_busca TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABELA DE TELEMETRIA DOS SENSORES IoT (SIMULADOS)
CREATE TABLE TB_AGRO_SENSOR_IOT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude NUMBER(9,6) NOT NULL,
    longitude NUMBER(9,6) NOT NULL,
    umidade_solo NUMBER(5,2) NOT NULL,    -- em % (0 a 100)
    temperatura_ar NUMBER(5,2) NOT NULL,  -- em °C
    ph_solo NUMBER(4,2),                 -- escala pH (0 a 14)
    data_leitura TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABELA DE LOGS DE INTERAÇÕES COM A IA GENERATIVA (GEMINI)
CREATE TABLE TB_AGRO_CHAT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem_user CLOB NOT NULL,
    resposta_ia CLOB NOT NULL,
    data_chat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COMENTÁRIOS DAS TABELAS
COMMENT ON TABLE TB_AGRO_BUSCA IS 'Tabela que armazena o histórico de coordenadas consultadas e seus dados de satélite.';
COMMENT ON TABLE TB_AGRO_SENSOR_IOT IS 'Tabela que armazena as leituras de telemetria dos sensores IoT de campo.';
COMMENT ON TABLE TB_AGRO_CHAT IS 'Tabela que armazena os logs de conversação do usuário com o assistente AgroSat AI.';

-- EXEMPLOS DE INSERTS DE TESTE:
-- INSERT INTO TB_AGRO_BUSCA (latitude, longitude, temp_media, ndvi_valor, classificacao_ndvi) VALUES (-23.5500, -46.6300, 22.5, 0.45, 'Vegetação Moderada');
-- INSERT INTO TB_AGRO_SENSOR_IOT (latitude, longitude, umidade_solo, temperatura_ar, ph_solo) VALUES (-23.5500, -46.6300, 65.2, 24.1, 6.5);
-- COMMIT;
